/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

/**
 *
 * @author User
 */
public class AdminUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        //administratorPanel = new javax.swing.JPanel();
        databaseOutput = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        logOffButton = new javax.swing.JButton();
        adminMainMenu = new javax.swing.JPanel();
        manageUserAccountsButton = new javax.swing.JButton();
        manageDepartmentsButton = new javax.swing.JButton();
        manageDegreesButton = new javax.swing.JButton();
        manageModulesButton = new javax.swing.JButton();
        databaseSelector = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        manageUserMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        forenameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        surnameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        roleSelector = new javax.swing.JComboBox<>();
        addUserButton = new javax.swing.JButton();
        removeUserButton = new javax.swing.JButton();
        manageUsersBackButton = new javax.swing.JButton();
        manageDepartmentMenu = new javax.swing.JPanel();
        manageDepartmentsBackButton = new javax.swing.JButton();
        manageDegreeMenu = new javax.swing.JPanel();
        manageDegreesBackButton = new javax.swing.JButton();
        manageModuleMenu = new javax.swing.JPanel();
        manageModulesBackButton = new javax.swing.JButton();

        jButton1.setText("Log Out");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //administratorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Administrator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 24))); // NOI18N
        //administratorPanel.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        databaseOutput.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        databaseOutput.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        databaseOutput.setViewportView(jTextArea1);

        logOffButton.setText("Log Off");

        //adminMainMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        /*
        manageUserAccountsButton.setText("Add User Account");
        manageUserAccountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showManageUserMenu(evt);
            }
        });

        manageDepartmentsButton.setText("Add Department");
        manageDepartmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showManageDepartmentMenu(evt);
            }
        });

        manageDegreesButton.setText("Add Degree");
        manageDegreesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showManageDegreeMenu(evt);
            }
        });

        manageModulesButton.setText("Add Module");
        manageModulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showManageModuleMenu(evt);
            }
        });*/

        databaseSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User Accounts (Staff)", "User Accounts (Students)", "Departments", "Degrees", "Modules" }));

        //jLabel7.setText("Choose infomation to show:");
        /*
        javax.swing.GroupLayout adminMainMenuLayout = new javax.swing.GroupLayout(adminMainMenu);
        adminMainMenu.setLayout(adminMainMenuLayout);
        adminMainMenuLayout.setHorizontalGroup(
            adminMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminMainMenuLayout.createSequentialGroup()
                        .addComponent(manageUserAccountsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel7))
                .addGap(5, 5, 5)
                .addGroup(adminMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(databaseSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminMainMenuLayout.createSequentialGroup()
                        .addComponent(manageDepartmentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageDegreesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageModulesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                .addGap(228, 228, 228))
        );
        adminMainMenuLayout.setVerticalGroup(
            adminMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageUserAccountsButton)
                    .addComponent(manageDepartmentsButton)
                    .addComponent(manageDegreesButton)
                    .addComponent(manageModulesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(databaseSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        */
        manageUserMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Manage User Accounts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12))); // NOI18N

        jLabel1.setText("Forename: ");

        forenameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forenameFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Surname: ");

        jLabel3.setText("Role: ");

        roleSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Adminstrator", "Registrar", "Teacher" }));

        addUserButton.setText("Add User");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        removeUserButton.setText("Remove User");

        manageUsersBackButton.setText("Back");
        manageUsersBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideManageUserMenu(evt);
            }
        });

        javax.swing.GroupLayout manageUserMenuLayout = new javax.swing.GroupLayout(manageUserMenu);
        manageUserMenu.setLayout(manageUserMenuLayout);
        manageUserMenuLayout.setHorizontalGroup(
            manageUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(manageUserMenuLayout.createSequentialGroup()
                        .addGroup(manageUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(manageUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roleSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forenameField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(manageUserMenuLayout.createSequentialGroup()
                        .addComponent(addUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageUsersBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        manageUserMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {forenameField, roleSelector, surnameField});

        manageUserMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addUserButton, manageUsersBackButton, removeUserButton});

        manageUserMenuLayout.setVerticalGroup(
            manageUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(forenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roleSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageUserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserButton)
                    .addComponent(removeUserButton)
                    .addComponent(manageUsersBackButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        manageUserMenu.setVisible(false);

        manageDepartmentMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Manage Departments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12))); // NOI18N

        manageDepartmentsBackButton.setText("Back");
        manageDepartmentsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideManageDeparmentMenu(evt);
            }
        });

        javax.swing.GroupLayout manageDepartmentMenuLayout = new javax.swing.GroupLayout(manageDepartmentMenu);
        manageDepartmentMenu.setLayout(manageDepartmentMenuLayout);
        manageDepartmentMenuLayout.setHorizontalGroup(
            manageDepartmentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageDepartmentMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageDepartmentsBackButton)
                .addContainerGap(828, Short.MAX_VALUE))
        );
        manageDepartmentMenuLayout.setVerticalGroup(
            manageDepartmentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageDepartmentMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manageDepartmentsBackButton)
                .addContainerGap())
        );

        manageDepartmentMenu.setVisible(false);

        manageDegreeMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Manage Degrees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12))); // NOI18N

        manageDegreesBackButton.setText("Back");
        manageDegreesBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideManageDegreeMenu(evt);
            }
        });

        javax.swing.GroupLayout manageDegreeMenuLayout = new javax.swing.GroupLayout(manageDegreeMenu);
        manageDegreeMenu.setLayout(manageDegreeMenuLayout);
        manageDegreeMenuLayout.setHorizontalGroup(
            manageDegreeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageDegreeMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageDegreesBackButton)
                .addContainerGap(828, Short.MAX_VALUE))
        );
        manageDegreeMenuLayout.setVerticalGroup(
            manageDegreeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageDegreeMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manageDegreesBackButton)
                .addContainerGap())
        );

        manageDegreeMenu.setVisible(false);

        manageModuleMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Manage Modules", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12))); // NOI18N

        manageModulesBackButton.setText("Back");
        manageModulesBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideManageModuleMenu(evt);
            }
        });

        javax.swing.GroupLayout manageModuleMenuLayout = new javax.swing.GroupLayout(manageModuleMenu);
        manageModuleMenu.setLayout(manageModuleMenuLayout);
        manageModuleMenuLayout.setHorizontalGroup(
            manageModuleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageModuleMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageModulesBackButton)
                .addContainerGap(828, Short.MAX_VALUE))
        );
        manageModuleMenuLayout.setVerticalGroup(
            manageModuleMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageModuleMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manageModulesBackButton)
                .addContainerGap())
        );

        manageModuleMenu.setVisible(false);

        javax.swing.GroupLayout administratorPanelLayout = new javax.swing.GroupLayout(administratorPanel);
        administratorPanel.setLayout(administratorPanelLayout);
        administratorPanelLayout.setHorizontalGroup(
            administratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administratorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(administratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(databaseOutput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(administratorPanelLayout.createSequentialGroup()
                        .addComponent(logOffButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, administratorPanelLayout.createSequentialGroup()
                        .addGroup(administratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(manageDepartmentMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageUserMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageDegreeMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageModuleMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        administratorPanelLayout.setVerticalGroup(
            administratorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administratorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageUserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageDepartmentMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageDegreeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageModuleMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(databaseOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOffButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(administratorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(administratorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forenameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forenameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forenameFieldActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserButtonActionPerformed
    /*
    private void showManageDepartmentMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showManageDepartmentMenu
        adminMainMenu.setVisible(false);
        manageDepartmentMenu.setVisible(true);
    }//GEN-LAST:event_showManageDepartmentMenu

    private void showManageUserMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showManageUserMenu
        adminMainMenu.setVisible(false);
        manageUserMenu.setVisible(true);
    }//GEN-LAST:event_showManageUserMenu*/

    private void hideManageDeparmentMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideManageDeparmentMenu
        adminMainMenu.setVisible(true);
        manageDepartmentMenu.setVisible(false);
    }//GEN-LAST:event_hideManageDeparmentMenu

    private void hideManageUserMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideManageUserMenu
        adminMainMenu.setVisible(true);
        manageUserMenu.setVisible(false);
    }//GEN-LAST:event_hideManageUserMenu
    /*
    private void showManageDegreeMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showManageDegreeMenu
        adminMainMenu.setVisible(false);
        manageDegreeMenu.setVisible(true);
    }//GEN-LAST:event_showManageDegreeMenu*/

    private void hideManageDegreeMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideManageDegreeMenu
        adminMainMenu.setVisible(true);
        manageDegreeMenu.setVisible(false);
    }//GEN-LAST:event_hideManageDegreeMenu
    /*
    private void showManageModuleMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showManageModuleMenu
        adminMainMenu.setVisible(false);
        manageModuleMenu.setVisible(true);
    }//GEN-LAST:event_showManageModuleMenu*/

    private void hideManageModuleMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideManageModuleMenu
        adminMainMenu.setVisible(true);
        manageModuleMenu.setVisible(false);
    }//GEN-LAST:event_hideManageModuleMenu

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JPanel adminMainMenu;
    private javax.swing.JPanel administratorPanel;
    private javax.swing.JScrollPane databaseOutput;
    //private javax.swing.JComboBox<String> databaseSelector;
    private javax.swing.JTextField forenameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    //private javax.swing.JLabel jLabel7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton logOffButton;
    private javax.swing.JPanel manageDegreeMenu;
    private javax.swing.JButton manageDegreesBackButton;
    //private javax.swing.JButton manageDegreesButton;
    private javax.swing.JPanel manageDepartmentMenu;
    private javax.swing.JButton manageDepartmentsBackButton;
    //private javax.swing.JButton manageDepartmentsButton;
    private javax.swing.JPanel manageModuleMenu;
    private javax.swing.JButton manageModulesBackButton;
    //private javax.swing.JButton manageModulesButton;
    //private javax.swing.JButton manageUserAccountsButton;
    private javax.swing.JPanel manageUserMenu;
    private javax.swing.JButton manageUsersBackButton;
    private javax.swing.JButton removeUserButton;
    private javax.swing.JComboBox<String> roleSelector;
    private javax.swing.JTextField surnameField;
    // End of variables declaration//GEN-END:variables
}
